# make ARCH=i386 SMALL=1 DEBUG=1

ARCH ?= amd64
SMALL = 0
DEBUG = 0
CC=clang

ARCHS32 := i386 arm
ARCHS64 := amd64 aarch64
ARCHS := $(ARCHS32) $(ARCHS64)

CFLAGS_i386 = -m32

CFLAGS += -pipe -fno-builtin -Wall -Wextra -fno-PIC -fno-ident -fno-stack-protector -U _FORTIFY_SOURCE -Wa,--noexecstack
LDFLAGS += -nostartfiles -nodefaultlibs -nostdlib -e z_start
LDFLAGS += -Wl,-Bsymbolic,--no-undefined,--build-id=none -static -Wl,-Ttext-segment=0x66660000
TARGET := foreign_dlopen_demo

ifeq "$(filter $(ARCH),$(ARCHS))" ""
  $(error ARCH='$(ARCH)' is not supported)
endif

ifeq "$(filter $(ARCH),$(ARCHS32))" "$(ARCH)"
  CFLAGS += -DELFCLASS=ELFCLASS32
else
  CFLAGS += -DELFCLASS=ELFCLASS64
endif

CFLAGS += $(CFLAGS_$(ARCH))
LDFLAGS += $(CFLAGS_$(ARCH))

ifeq "$(DEBUG)" "1"
  CFLAGS += -O0 -g
else
  CFLAGS += -fvisibility=hidden
  # Disable unwind info to make prog smaller.
  CFLAGS += -fno-asynchronous-unwind-tables -fno-unwind-tables
  #CFLAGS += -Os # causes issues on arm z_printf, and 
                 #
		 # any optimizations cause issues on amd64
		 # ?
		 #
		 # let's take a risk
  CFLAGS += -Os -fno-pie
  # Strip later
  # LDFLAGS += -s
endif

ASFLAGS = $(CFLAGS)

OBJS := loader.o z_err.o z_printf.o z_syscalls.o z_utils.o fdl_resolve.o
OBJS += $(patsubst %.S,%.o, $(wildcard $(ARCH)/*.S))

ifeq "$(SMALL)" "1"
  OBJS := $(filter-out z_printf.%,$(OBJS))
  OBJS := $(filter-out z_err.%,$(OBJS))
  CFLAGS += -DZ_SMALL
endif

.PHONY: clean all

all: $(TARGET)

foreign_dlopen_demo: foreign_dlopen_demo.o $(OBJS)

clean:
	rm -rf *.o $(TARGET) */*.o

